const data = [
    {
        id:"1",
        paperTitle:" Software development life cycle testing analysis: A reliability approach. ",
        paperlink:"http://nonlinearstudies.com/index.php/mesa/article/view/1047",
        authors:"Nupur Goyal and Mangay Ram",
        description:"Mathematics in Engineering, Science & Aerospace.",
        issuepage:"(2014), 5(3), 313-329.",
        download:"Dowanload",
    },
    {
        id:"2",
        paperTitle:" Automated teller machine performance evaluation through cash transactions.",
        paperlink:"http://nonlinearstudies.com/index.php/mesa/article/view/1161",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"3",
        paperTitle:"Automotive water cooling system analysis subject to time dependence and failure issues.",
        paperlink:"https://www.igi-global.com/article/automotive-water-cooling-system-analysis-subject-to-time-dependence-and-failure-issues/146820",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"4",
        paperTitle:"On reliability analysis of a multi-state (k+ l)-out-of-n: F system with partial failure.",
        paperlink:"http://nonlinearstudies.com/index.php/nonlinear/article/view/1343",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"5",
        paperTitle:"Thermal Power Plant Modelling with Fault Coverage Stochastically.",
        paperlink:"https://www.igi-global.com/article/thermal-power-plant-modelling-with-fault-coverage-stochastically/158068",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"6",
        paperTitle:"Mathematical modeling for genesis of Alzheimer disease through Markov process.",
        paperlink:"http://sphinxsai.com/2016/ph_vol9_no7/1/(189-199)V9N7PT.pdf",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"7",
        paperTitle:"An Approach to Investigating Reliability Indices for Tree Topology Network.",
        paperlink:"https://www.tandfonline.com/doi/abs/10.1080/01969722.2016.1209378?journalCode=ucbs20",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"8",
        paperTitle:"Automated Teller Machine Network Inspection under Stochastic Modelling.",
        paperlink:"http://www.jestr.org/downloads/Volume9Issue5/fulltext1952016.pdf",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"9",
        paperTitle:"Autonomous robot performance evaluation with rework.",
        paperlink:"https://www.inderscienceonline.com/doi/abs/10.1504/IJRS.2016.081610",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"10",
        paperTitle:"Stochastic modelling of a wind electric generating power plant.",
        paperlink:"https://www.emeraldinsight.com/doi/abs/10.1108/IJQRM-09-2015-0143",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"11",
        paperTitle:"Estimation of performability parameters of centre heating system.",
        paperlink:"http://nonlinearstudies.com/index.php/nonlinear/article/view/1463",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"12",
        paperTitle:"Sensitivity analysis of a three-unit series system under k-out-of-n redundancy.",
        paperlink:"https://www.emeraldinsight.com/doi/abs/10.1108/IJQRM-07-2016-0106",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"13",
        paperTitle:"Performability of solar thermal power plant under reliability characteristics.",
        paperlink:"https://link.springer.com/article/10.1007/s13198-016-0452-0",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"14",
        paperTitle:"Exploiting multi-path analysis of a computer numerical control machining system.",
        paperlink:"http://www.novapublishers.org/catalog/product_info.php?products_id=63528",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"15",
        paperTitle:"Software reliability growth modeling for agile software development.",
        paperlink:"https://www.amcs.uz.zgora.pl/?action=paper&paper=1402",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"16",
        paperTitle:"Sensitivity assessment of air and refrigeration.",
        paperlink:"https://journalskuwait.org/kjs/index.php/KJS/article/view/1986",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"17",
        paperTitle:"Stochastic design exploration with rework of flexible manufacturing system under copula-coverage approach.",
        paperlink:"https://www.worldscientific.com/doi/abs/10.1142/S0218539318500079",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"18",
        paperTitle:"Bi-directional system analysis under copula-coverage approach.",
        paperlink:"https://www.tandfonline.com/doi/abs/10.1080/03610918.2017.1327068",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"19",
        paperTitle:"An analysis of hierarchical software-defined network control plane: a reliability approach.",
        paperlink:"https://www.worldscientific.com/doi/10.1142/S0218539320500102",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"20",
        paperTitle:" Fuzzy Reliability Based on Hesitant and Dual Hesitant Fuzzy Set Evaluation.",
        paperlink:"https://ijmems.in/volumes/volume6/number1/10-IJMEMS-SBS19-15-6-1-166-179-2021.pdf",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"21",
        paperTitle:"Reliability measures and profit exploration of windmill water-pumping systems incorporating warranty and two types of repair.",
        paperlink:"https://www.mdpi.com/2227-7390/9/8/822",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"22",
        paperTitle:"Analysis of Network Reliability Characteristics and Importance of Components in a Communication Network.",
        paperlink:"https://www.mdpi.com/2227-7390/9/12/1347",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"23",
        paperTitle:"Evaluating and improving a content delivery network (CDN) workflow using stochastic modelling.",
        paperlink:"https://journals.riverpublishers.com/index.php/JCSANDM/article/view/6219",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"24",
        paperTitle:"Multi-objective optimization of superstructure for biodiesel production from biomass. ",
        paperlink:"http://divk.inovacionicentar.rs/ivk/ivk21/ivk21SI-7.html",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"25",
        paperTitle:"Signature analysis of a combinatory system. Materials Today: Proceedings.",
        paperlink:"https://www.sciencedirect.com/science/article/pii/S2214785321022604",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"26",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"27",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"28",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"29",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"30",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"31",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"32",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"33",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"34",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"35",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"36",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"37",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"38",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"39",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"40",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"41",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"42",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"43",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"44",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"45",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"46",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    
    {
        id:"47",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"48",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"49",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    {
        id:"50",
        paperTitle:" ",
        paperlink:"",
        description:"Published in ",
        download:"Dowanload",
    },
    

]

export default data